name: Enabled tests counter

on:
  push

jobs:
  counter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Build counter
        run: mvn clean package -PEnabledTestsCounter -DskipTests
      - name: Rename counter
        run: cp transpiler/target/transpiler-*-jar-with-dependencies.jar counter.jar
      - name: Run counter
        run: java -jar counter.jar