name: Integration Tests

on:
  schedule:
    - cron: '55 07 * * *'

jobs:
  ParserPrinter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
          cache: 'maven'
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: Run integration test
        run: mvn clean verify -B -Dit.test=ParserPrinterIT -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  CPython:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
          cache: 'maven'
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: Run integration test
        run: mvn clean verify -B -Dit.test=CPythonIT -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  Django:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
          cache: 'maven'
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: Run integration test
        run: mvn clean verify -B -Dit.test=DjangoIT -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
